### ISSUE TITLE
Special hours doesn't work for weekends

### ISSUE THREAD

**Issue by hgc2002** [antoniandre/vue-cal-v4#243]
I'm trying to paint weekends in a different color, using the "special-hours" feature. The calendar is painted ok but nothing on weekend get different (coloured) than the rest.

I'm using VueJS 2.6.11, and VueCal 2.24.7

Here is my component configuration at the template section:
`
<vue-cal style="height: 30em" locale="es" today-button :special-hours="weekendDays"
:time-from="9 * 60" :time-to="20 * 60" :time-step="30"/>
`

Inside the default export section (at data):
`
weekendDays: { 6: weekendHours, 7: weekendHours }
`

also:
`
const weekendHours = { from: 0 * 60, to: 23 * 60, class: 'weekend-hours'}  // full day
`

and the style:

`
    .weekend-hours {
        background-color: rgba(255, 255, 0, 0.2);
        border: solid rgba(255, 210, 0, 0.6);
        border-width: 2px 0;
    }
`

Any idea?
Regards,
Herman.

**Comment by antoniandre** [comment]
Hi @hgc2002, 
Thanks for reporting, this is now fixed in version 2.24.8!

___

Please note that the documentation is up to date with the alpha release and a little ahead the 2.24.8 version, a few things may differ while using the current latest version - check the V 3.0 alpha release notes. I should release the stable version end of next week.

**Comment by hgc2002** [comment]
@antoniandre ok thanks. 
uhm, so my code is about to change to adapt to the next stable version, right?
currently the problem is still happening in 2.24.8 (just updated) so I'll wait for the next version to try again.

**Comment by hgc2002** [comment]
Ok, fixed. I've found that the scoped style was not being added to the web page. Little bit strange. As soon as I put the style as global, it worked like a charm ...
